"""Auto-generated claim-packet report: timestamp, evidence frame, risk
classification, contract clause, recommended action — the master plan's
Tier 1 "auto-generated claim packet (PDF)" feature, tying the system to
real insurance/claims workflows.

One shared context dict feeds two renderers:
- render_html(): the Jinja2 template as a plain HTML string (fast preview,
  what GET /reports/{id}?format=html returns).
- render_pdf(): the same data laid out as an actual PDF file with reportlab,
  since that's what an insurance claim needs to attach.
"""
import io
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.core.constants import BEHAVIOR_VOCABULARY
from app.models.event import Event
from app.services import event_service
from app.utils.timestamps import format_seconds

TEMPLATES_DIR = Path(__file__).resolve().parents[3] / "reports" / "templates"

_env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)), autoescape=select_autoescape(["html"]))


def _report_context(event: Event) -> dict:
    data = event_service.to_event_read_dict(event)
    data["start_time_display"] = format_seconds(event.start_time_seconds)
    data["end_time_display"] = format_seconds(event.end_time_seconds)
    data["behavior_labels"] = [
        BEHAVIOR_VOCABULARY.get(code, {}).get("label", code) for code in data["behaviors"]
    ]
    return data


def render_html(event: Event) -> str:
    template = _env.get_template("incident_report.html")
    return template.render(**_report_context(event))


def render_pdf(event: Event) -> bytes:
    context = _report_context(event)
    styles = getSampleStyleSheet()
    cell_style = styles["Normal"]
    label_style = ParagraphStyle("Label", parent=styles["Normal"], textColor=colors.grey, fontSize=9)

    def cell(text: str):
        return Paragraph(str(text), cell_style)

    product = context["product"]
    product_display = f"{product.name} ({product.sku})" if product else "unidentified"

    exposure = context["estimated_exposure_inr"]
    exposure_display = f"₹{exposure:,.0f} (industry-indicative estimate)" if exposure is not None else "—"

    rows = [
        [cell("Dock"), cell(context["dock"] or "unknown")],
        [cell("Time window"), cell(f"{context['start_time_display']} – {context['end_time_display']}")],
        [cell("Risk level"), cell(context["risk_level"])],
        [cell("Risk score"), cell(f"{context['risk_score']} / 100")],
        [cell("Confidence"), cell(f"{context['confidence']:.0%}")],
        [cell("Status"), cell(context["status"])],
        [cell("Behaviors observed"), cell(", ".join(context["behavior_labels"]) or "—")],
        [cell("Product"), cell(product_display)],
        [cell("Contract clause violated"), cell(context["contract_clause_violated"] or "None recorded")],
        [cell("Recommended action"), cell(context["recommended_action"] or "—")],
        [cell("Estimated exposure"), cell(exposure_display)],
    ]

    table = Table(rows, colWidths=[5 * cm, 11 * cm])
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )

    story = [
        Paragraph("Fragility Passport — Incident Claim Packet", styles["Title"]),
        Paragraph(f"Event {context['public_id']}", styles["Heading2"]),
        Spacer(1, 0.5 * cm),
        table,
        Spacer(1, 0.5 * cm),
    ]

    if context["evidence_description"]:
        story.append(Paragraph("AI evidence description", styles["Heading3"]))
        story.append(Paragraph(context["evidence_description"], cell_style))
        story.append(Spacer(1, 0.3 * cm))

    for path in context["evidence_paths"]:
        image_path = Path(path)
        if image_path.exists():
            story.append(Paragraph("Evidence frame", styles["Heading3"]))
            story.append(Image(str(image_path), width=12 * cm, height=8 * cm, kind="proportional"))
            story.append(Spacer(1, 0.3 * cm))

    story.append(
        Paragraph(
            "Risk classification and ₹ exposure figures are generated by an automated risk model "
            "and are industry-indicative estimates, not audited valuations.",
            label_style,
        )
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    doc.build(story)
    return buffer.getvalue()
